USE BARBER;

CREATE TABLE USUARIO(
ID_LOJA INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
NOME_LOJA VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
CPF CHAR(12),
NOME VARCHAR(100) NOT NULL,
SOBRENOME VARCHAR(100) NOT NULL,
SENHA VARCHAR(100) NOT NULL,
TELEFONE VARCHAR(12) NOT NULL,
ADMIN ENUM('S','N') NOT NULL,
ATIVO ENUM('S','N') NOT NULL,
DATA_CRIACAO DATETIME NOT NULL DEFAULT NOW()
);

CREATE TABLE ENDERECO(
ID_ENDERECO INT(100) PRIMARY KEY NOT NULL AUTO_INCREMENT,
ESTADO CHAR(2) NOT NULL,
MUNICIO VARCHAR(20) NOT NULL,
BAIRRO VARCHAR(20) NOT NULL,
RUA VARCHAR(20) NOT NULL,
NUMERO INT(5) NOT NULL,
CEP CHAR(8),
FK_IDLOJA INT(10),
FOREIGN KEY(FK_IDLOJA)
REFERENCES USUARIO(ID_LOJA)
);


CREATE TABLE MODULO(
ID_MODULO INT(100) NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOME_MODULO VARCHAR(100) NOT NULL,
VALOR_MODULO FLOAT(10,2) NOT NULL,
FK_IDLOJA INT(10),
FOREIGN KEY(FK_IDLOJA)
REFERENCES USUARIO(ID_LOJA)
);


CREATE TABLE AGENDAMENTO(
ID_AGENDAMENTO INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
NOME_CLIENTE VARCHAR(50) NOT NULL,
MODULO VARCHAR(100),
CELULAR_CLIENTE CHAR(12) NOT NULL,
DATA_AGD DATETIME,
VALOR FLOAT(10,2) NOT NULL,
STATUS_PED ENUM('PENDENTE', 'AGENDADO', 'FINALIZADO'),
FK_IDLOJA INT(10),
FOREIGN KEY(FK_IDLOJA)
REFERENCES USUARIO(ID_LOJA)
);

SHOW TABLES;

SELECT * FROM AGENDAMENTO;
SELECT * FROM USUARIO;
SELECT * FROM MODULO;
SELECT * FROM ENDERECO;


INSERT INTO USUARIO VALUES(
NULL, "DANIEL&EDUARDO","EFIASN@GMAIL.COM", "179815157774", "EDUARDO", "MENDES", "1234", "27988124574", "S", "S", NOW()
);

INSERT INTO MODULO VALUES(
NULL, "DISFARÇADO", 20.00, 3);

INSERT INTO MODULO VALUES(
NULL, "MAQUINA 1", 10.00, 3);


INSERT INTO ENDERECO VALUES(
NULL, "ES", "VILA VELHA", "RIO MARINHO", "ITAPINA", 100, "29112540", 3
);


# JOÃO FEZ O PEDIDO
INSERT INTO AGENDAMENTO VALUES(NULL, "JOÃO", 
	(SELECT NOME_MODULO FROM MODULO WHERE ID_MODULO = 1),
"27988329457", NOW(),
	(SELECT VALOR_MODULO FROM MODULO WHERE ID_MODULO = 1),
"PENDENTE",
3
);

#FELIPE FEZ O PEDIDO
INSERT INTO AGENDAMENTO VALUES(NULL, "FELIPE", 
	(SELECT NOME_MODULO FROM MODULO WHERE ID_MODULO = 2),
"27988329457", NOW(),
	(SELECT VALOR_MODULO FROM MODULO WHERE ID_MODULO = 2),
"PENDENTE",
3
);

# MATHEUS FAZ O PEDIDO
INSERT INTO AGENDAMENTO VALUES(NULL, "MATHEUS", 
	(SELECT NOME_MODULO FROM MODULO WHERE ID_MODULO = 1),
"27988329457", NOW(),
	(SELECT VALOR_MODULO FROM MODULO WHERE ID_MODULO = 1),
"PENDENTE",
3
);


# LOJA DANIEL&EDUARDO ACEITA
UPDATE AGENDAMENTO
SET STATUS_PED = "AGENDADO"
WHERE ID_AGENDAMENTO = 1;

# LOJA DANIEL&EDUARDO FINALIZA UM CLIENTE
UPDATE AGENDAMENTO
SET STATUS_PED = "FINALIZADO"
WHERE ID_AGENDAMENTO = 3;

#VIEW DE FINANCEIRO
CREATE VIEW FINANCEIRO AS
SELECT u.ID_LOJA, 
	   u.NOME_LOJA, 
	   u.NOME, SUM(a.VALOR) AS VALOR
FROM USUARIO u
INNER JOIN AGENDAMENTO a
ON u.ID_LOJA = a.FK_IDLOJA
WHERE u.ID_LOJA = 3
AND a.STATUS_PED = "FINALIZADO";

SELECT * FROM FINANCEIRO;

#PROCEDURES PARA ADICIONAR FILIAL FINANCEIRO
DELIMITER @
CREATE PROCEDURE ADICIONAR_FILIAL(ID_LOJA INT(10))
BEGIN
SELECT u.ID_LOJA, 
	   u.NOME_LOJA, 
	   u.NOME, SUM(a.VALOR) AS VALOR
FROM USUARIO u
INNER JOIN AGENDAMENTO a
ON u.ID_LOJA = a.FK_IDLOJA
WHERE u.ID_LOJA = ID_LOJA;
END
@

#DROP PROCEDURE ADICIONAR_FILIAL;
#CALL ADICIONAR_FILIAL(3);